pollProject/pollApp/urls.py
from .import views
from django.urls import path

app_name='pollApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('pollApp/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
    path('signin/', views.signin, name='poll-login'),
    path('signout/', views.signout, name='poll-logout'),
    path('count/', views.voted, name='voted'),
]

pollProject/pollProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pollApp.urls',namespace='pollApp')),
]

pollProject/pollApp/models.py
from django.db import models
from django.contrib.auth.models import User
import django.utils.datetime_safe
from django.db import migrations, models
from datetime import datetime



# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# class Vote(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
#     voted_at = models.DateTimeField(auto_now_add=True)

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Question, on_delete=models.CASCADE)
    option = models.ForeignKey(Choice, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.now, null=True, blank=True)

    def __str__(self):
        return f"{self.user} selected {self.option.choice_text} at {self.timestamp}"

pollProject/pollApp/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponseRedirect,HttpResponse
from .models import Question
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from .models import Vote
import django.utils.datetime_safe
from django.db import migrations, models
from datetime import datetime


# Create your views here.

@login_required(login_url="signin/")
def index(request):
    
    latest = Question.objects.order_by('-pub_date')[:5] #getting all the questions
    context = {
        'latest':latest,
    }
    return render(request,'pollApp/index.html',context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) #ekta specific question er jonno etar corresponding option gula dekhacche
    return render(request,'pollApp/detail.html',{'question': question})


def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id) 
    # vote_count=get_object_or_404(Question,pk=question_id)
    # Profile=get_object_or_404(user=request.user)
    print(question)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])  #ami ekhane select korsi choice
    except:
        return render(request, 'pollApp/detail.html',{'question':question,'error_message':"Please select a choice"})
    else:
        selected_choice.votes += 1
        # selected_choice.option += selected_choice
        selected_choice.save()
        user=request.user
        record_vote(user=user, question=question, choice=selected_choice)

        return HttpResponseRedirect(reverse('pollApp:results', args=[question_id], ))

# def voted(request):
#     try:
#         # question=get_object_or_404(Question,pk=question_id)
#         Profile=get_object_or_404(user=request.user)
#         # selected_choice=question.choice_set.get(pk=request.POST['choice'])
#     except Exception as e:
#         profile= None
#         print('Exception : ', e)
#         context={
#             'profile': profile,
#         }
#         return render(request,'pollApp/profile.html',context)

def voted(request):
    Profile=Vote.objects.all()
    for a in Profile:
        print(a)
    context={
        'profile': Profile,
    }
    return render(request,'pollApp/profile.html',context) 




# @login_required(login_url="signin/")
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         return render(request, 'pollApp/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.user.add(request.user)
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('pollApp:results', args=(question.id,)))



def results(request, question_id):
    question= get_object_or_404(Question,pk=question_id)
    return render(request, 'pollApp/result.html', {'question':question})

def signin(request):
    if(request.method=='GET'):
        return render(request, 'pollApp/login.html')
    elif(request.method=='POST'):
        u=request.POST.get('username','')
        p=request.POST.get('password','')

        res=authenticate(username=u,password=p)
        if(res is None):
            return HttpResponse('<h1>Sign In Failed. You cannot Vote</h2>')
        else:
            login(request,res)
            return redirect('pollApp:index')

def signout(request):
    logout(request)
    return redirect('pollApp:poll-login')

def record_vote(user, question , choice ):
    print(user, question , choice)
    timestamp = models.DateTimeField(auto_now_add=True)
    voted = Vote(user=user,poll=question,option=choice)
    voted.save()
     

pollProject/pollApp/templates/pollApp/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>
    {% if error_message %} <p><b>{{ error_message }}</b></p> {% endif %}

    <form action="{% url 'pollApp:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
            <input type="submit" value="vote">


    </form>
</body>

</html>

pollProject/pollApp/templates/pollApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if latest %}
    <ul>
    {% for x in latest %}
        <li><a href="/pollApp/{{ x.id }}/">{{ x.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>
</html>

pollProject/pollApp/templates/pollApp/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form class="ui form" method="POST" action="{% url 'pollApp:poll-login' %}">
         {% csrf_token %}
        <div class="field">
          <label>User Name</label>
          <input type="text" name="username" placeholder="User Name">
        </div>
        <div class="field">
          <label>Password</label>
          <input type="password" name="password" placeholder="Password">
        </div>
        <button class="ui button" type="submit">Login</button>
      </form>
</body>
</html>

pollProject/pollApp/templates/pollApp/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <ul>
        {% for vote in profile %}
          <li>{{ vote.user }} voted for {{ vote.option }} at {{ vote.timestamp }}</li>
        {% endfor %}
        </ul>
    {% comment %} {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}-->{{ choice.votes }} </li>
    {% endfor %}



    <a href="{% url 'pollApp:detail' question.id %}">vote again</a>
    <button><a href="{% url 'pollApp:poll-logout' %}">Logout</a></button> {% endcomment %}

</body>

</html>

pollProject/pollApp/templates/pollApp/result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}-->{{ choice.votes }} </li>
    {% endfor %}



    <a href="{% url 'pollApp:detail' question.id %}">vote again</a>
    <button><a href="{% url 'pollApp:poll-logout' %}">Logout</a></button>

</body>

</html>